### ISSUE TITLE
文章中还延续了之前semantic flow的思想吗

### ISSUE THREAD

**Issue by MaybeShewill-CV** [lxtGH/BSSeg#1]
如题。先咨询下大佬（偷个懒还没仔细看文章）：）

**Comment by lxtGH** [comment]
感谢关注！（不是大佬）还不太一样哈。这个里面主要是关注的是物体的边缘。flow warping只是一种实现的方式。

**Comment by MaybeShewill-CV** [comment]
@lxtGH 嗯，周末仔细看了下文章。👍
