### ISSUE TITLE
Could you publish codes soon?

### ISSUE THREAD

**Issue by wenchen4321** [lxtGH/BSSeg#2]
What a amazing work! I am very interested about this job. Could you publish the codes? Thank you very much!

**Comment by lxtGH** [comment]
Hi! Thanks for your attention. We will release the code within a month.

**Comment by nishnik** [comment]
Hi @lxtGH 

Are you publishing the code in this week?

**Comment by ai1urus** [comment]
Hi @lxtGH 
Will the code be released in July or before August 15th?

**Comment by lxtGH** [comment]
@nishnik @ai1urus Hi ! Thanks for your attention.  Since the paper is still under review. We will release the code according to the review.

**Comment by lxtGH** [comment]
The code is released
