### ISSUE TITLE
代码开源问题

### ISSUE THREAD

**Issue by Wu-ZJ** [lxtGH/BSSeg#3]
作者您好，阅读了这篇文章，对您的工作很感兴趣，不知道啥时候可以开源呀！

**Comment by lxtGH** [comment]
@manguoooneil 你好！谢谢关注。我们打算等待paper review的情况来决定。预计会在11月底前 release code和 model。

**Comment by lxtGH** [comment]
The code is released ~

**Comment by weiaicunzai** [comment]
> The code is released ~

你好，请问这篇论文中了什么呢？谢谢。
